### ISSUE TITLE
[image2rtsp-1] [ERROR] [1702255704.581977518] [image2rtsp]: GST: image format 'yuv422_yuy2' unknown

### ISSUE THREAD

**Issue by xiaotaozide** [45kmh/image2rtsp#1]
May I ask what I should do if "[image2rtsp-1] [ERROR] [1702255704.581977518] [image2rtsp]: GST: image format 'yuv422_yuy2' unknown" is displayed when I pull the stream with vlc, thanks!

**Comment by maladzenkau** [comment]
Hi, this means that the format of the images published in the topic is not supported at the moment. Currently, the supported formats are:**"RGB", "RGB16", "RGBA", "RGBA16", "BGR", "BGR16", "BGRA", "BGRA16", "GRAY8", "GRAY16_LE"**. I will try to add more formats later, as I am quite busy right now. If you need a solution immediately, you can try first to convert "yuv422" into "RGB" ([Convert 422 to RGB](https://paulbourke.net/dataformats/yuv/)). Please let me know if you have any further questions or concerns.

**Comment by xiaotaozide** [comment]
Ok, I will try "yuv422" to "RGB" first, thank you very much!

**Comment by maladzenkau** [comment]
Hello, just for your information, I have recently added support for "yuv422_yuy2".

**Comment by xiaotaozide** [comment]
Ok, thank you very much!
