### ISSUE TITLE
Unknown CMake command "pkg_check_modules"

### ISSUE THREAD

**Issue by dustydins** [45kmh/image2rtsp#6]
I'm running Ubuntu 22.04/ROS2 Humble. 

At `colcon build --packages-select image2rtsp` I receive the following error:

```Starting >>> image2rtsp
--- stderr: image2rtsp
CMake Error at CMakeLists.txt:22 (pkg_check_modules):
  Unknown CMake command "pkg_check_modules".


gmake: *** [Makefile:322: cmake_check_build_system] Error 1
---
Failed   <<< image2rtsp [0.47s, exited with code 2]

Summary: 0 packages finished [0.69s]
  1 package failed: image2rtsp
  1 package had stderr output: image2rtsp
```
Any help would be much appreciated!

**Comment by dustydins** [comment]
After running `dpkg -l | grep pkg-config` I receive the following output:

```
ii  pkg-config                                         0.29.2-1ubuntu3                                   amd64        manage compile and link flags for libraries
ii  python3-colcon-pkg-config                          0.1.0-1                                           all          Extension for colcon adding an environment variable to find
```

**Comment by dustydins** [comment]
I added the following line at CMakeLists.txt:19 -

`find_package(PkgConfig REQUIRED)`

Seems to be working fine now

**Comment by maladzenkau** [comment]
Hi, @dustydins. 
Apologies for being away this weekend. I’m glad you’ve already found the solution on your own. I’ll make the necessary corrections to CMake as well. Thank you!
